name: my_great_app
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.2+3

environment:
  sdk: '>=2.19.6 <3.0.0'


dependencies:
  provider: ^6.0.5
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  get_it: ^7.3.0
  auto_route: ^7.1.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  auto_route_generator: ^7.0.0
  flutter_lints: ^2.0.0
  build_runner: ^2.3.3

flutter:
  uses-material-design: true

  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  fonts:
    - family: Ysabeau
      fonts:
        - asset: assets/fonts/Ysabeau-Regular.ttf
    - family: PressStart
      fonts:
        - asset: assets/fonts/PressStart2P-Regular.ttf
